service: myWallet

frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-dotenv-plugin
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-offline

custom: ${file(custom.yml)}

resources: ${file(resources.yml)}

provider: ${file(provider.yml)}

functions: ${file(functions.yml)}

package:
  excludeDevDependencies: true
